{"name": "test_recipes", "status": "failed", "statusDetails": {"message": "AssertionError: Expected https://eda.ru/recepty/zavtraki/sirniki-iz-tvoroga-18506, but got https://eda.ru/recepty", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3754d54242fda77731dd8c84043fdd1e\")>\n\n    def test_recipes(browser):\n        with allure.step(\"Test recipes\"):\n            recipes_page = RecopesPage(browser)\n    \n        with allure.step(\"open\"):\n            recipes_page.open()\n            sleep(0.5)\n    \n        with allure.step(\"open_recopes\"):\n            recipes_page.open_recopes()\n    \n        with allure.step(\"scroll\"):\n            recipes_page.scroll()\n    \n        with allure.step(\"recipe_ingridients\"):\n            recipes_page.recipe_ingridients()\n    \n        with allure.step(\"portion_plus\"):\n            recipes_page.portion_plus()\n    \n        with allure.step(\"test_url\"):\n>           recipes_page.test_url()\n\ntests\\test_recipes.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.recipes_page.RecopesPage object at 0x0000010D6C647B60>\n\n    def test_url(self):\n        expected_url = \"https://eda.ru/recepty/zavtraki/sirniki-iz-tvoroga-18506\"\n        actual_url = self.browser.current_url\n>       assert actual_url == expected_url, f\"Expected {expected_url}, but got {actual_url}\"\nE       AssertionError: Expected https://eda.ru/recepty/zavtraki/sirniki-iz-tvoroga-18506, but got https://eda.ru/recepty\n\npages\\recipes_page.py:32: AssertionError"}, "steps": [{"name": "Test recipes", "status": "passed", "start": 1717034122985, "stop": 1717034122985}, {"name": "open", "status": "passed", "start": 1717034122985, "stop": 1717034133663}, {"name": "open_recopes", "status": "passed", "start": 1717034133663, "stop": 1717034135914}, {"name": "scroll", "status": "passed", "start": 1717034135914, "stop": 1717034136054}, {"name": "recipe_ingridients", "status": "passed", "start": 1717034136055, "stop": 1717034138207}, {"name": "portion_plus", "status": "passed", "start": 1717034138207, "stop": 1717034142246}, {"name": "test_url", "status": "failed", "statusDetails": {"message": "AssertionError: Expected https://eda.ru/recepty/zavtraki/sirniki-iz-tvoroga-18506, but got https://eda.ru/recepty\n", "trace": "  File \"C:\\Users\\Админ\\PycharmProjects\\Vlad-7\\tests\\test_recipes.py\", line 27, in test_recipes\n    recipes_page.test_url()\n  File \"C:\\Users\\Админ\\PycharmProjects\\Vlad-7\\pages\\recipes_page.py\", line 32, in test_url\n    assert actual_url == expected_url, f\"Expected {expected_url}, but got {actual_url}\"\n"}, "start": 1717034142246, "stop": 1717034142248}], "start": 1717034122985, "stop": 1717034142279, "uuid": "dd6dac74-22b5-4ed1-824e-cc16d76f1203", "historyId": "0e0f9b36bb6865d0090c16945f1e5006", "testCaseId": "0e0f9b36bb6865d0090c16945f1e5006", "fullName": "tests.test_recipes#test_recipes", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_recipes"}, {"name": "host", "value": "DESKTOP-0BM2ERP"}, {"name": "thread", "value": "8136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_recipes"}]}